site_name: Codelogium
site_description: Developer logs, notes, and learning paths
site_url: https://codelogium.github.io
repo_url: https://github.com/codelogium/codelogium
repo_name: codelogium/codelogium
edit_uri: "GitHub"

theme:
  name: material
  language: en
  #custom_dir: overrides
  #logo: assets/logo.png          
  #favicon: assets/favicon.ico
  palette:
    - scheme: default
      toggle:
      primary: teal
      accent: teal
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.top
    - navigation.tabs
    # - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    # - header.autohide
    - search.suggest
    # - toc.integrate
    - content.code.annotate
    - search.highlight

markdown_extensions:
  - toc:
      title: "Table of content"
      permalink: "¶"  # Use the pilcrow sign
      # Or use other symbols like "§", "#", "↩", "🔗", etc.
      permalink_title: Permalink 
      toc_depth: "1-6"
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.details
  - attr_list
  - tables
  
nav:
  - Home: index.md
  - Databases:
      - Overview: databases/index.md
      - Postgres vs H2: blog/post/database/postgres-vs-h2.md
      - Hibernate Tips: blog/post/database/hibernate-tips.md
  - Java: 
      - java/index.md
      - blog/post/java/generic-types.md
  - Spring:
      - Overview: spring/index.md
      - JWT Auth: spring/jwt-auth.md
  - Lab:
      - Overview: lab/index.md
  - Blog:
      - Overview: blog/index.md
      - Random Thought: blog/random-thought.md
      - Things I Learned: blog/things-i-learned.md

extra:
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alfahami
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alfahami
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/al_fahami

copyright: "© 2025 Codelogium • Crafted with curiosity accompanied by a cup of tea."

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
  - awesome-pages:
  - blog:
  #- blogging:
  - categories:
  - tags:
  # - git-revision-date-localized:
      fallback_to_build_date: false