site_name: Codelogium
site_description: Developer logs, notes, and learning paths
site_url: https://codelogium.github.io
repo_url: https://github.com/codelogium/codelogium
repo_name: GitHub
edit_uri: ""

theme:
  name: material
  language: en
  #logo: assets/logo.png          
  #favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: teal
      accent: orange
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - toc.integrate
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - #header.autohide
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.details
  - attr_list
  - tables

nav:
  - Home: index.md
  - Databases:
      - Overview: databases/index.md
      - Postgres vs H2: databases/postgres-vs-h2.md
      - Hibernate Tips: databases/hibernate-tips.md
  - Java:
      - Overview: java/index.md
      - Some Java Post: java/some-java-post.md
  - Spring:
      - Overview: spring/index.md
      - JWT Auth: spring/jwt-auth.md
  - Blog:
      - Overview: blog/index.md
      - Random Thought: blog/random-thought.md
      - Things I Learned: blog/things-i-learned.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codelogium
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alfahami
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
  copyright:
    "© 2025 Codelogium. Crafted with curiosity accompanied by a cup of coffee."


extra_css:
  - stylesheets/extra.css


plugins:
  - search:
  - awesome-pages:
  - blog:
  - git-revision-date-localized:
      fallback_to_build_date: true


