site_name: Codelogium
site_url: https://codelogium.github.io
theme:
  name: material
  language: en
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    navigation.instant
    navigation.instant.prefetch
    navigation.instant.progress
    navigation.instant.preview
    navigation.tracking
    navigation.tabs
    navigation.tabs.sticky
    navigation.sections
    navigation.expand
    navigation.path
    toc.follow
    toc.integrate
    navigation.top
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Databases:
      - Overview: databases/index.md
      - Postgres vs H2: databases/postgres-vs-h2.md
      - Hibernate Tips: databases/hibernate-tips.md
  - Java:
      - Overview: java/index.md
      - Some Java Post: java/some-java-post.md
  - Spring:
      - Overview: spring/index.md
      - JWT Auth: spring/jwt-auth.md
  - Blog:
      - Overview: blog/index.md
      - Random Thought: blog/random-thought.md
      - Things I Learned: blog/things-i-learned.md

plugins:
  - search:
  - blog: