site_name: Codelogium
site_url: https://codelogium.github.io
theme:
  name: material
  language: en
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    navigation.instant
    navigation.instant.prefetch
    navigation.instant.progress
    navigation.instant.preview
    navigation.tracking
    navigation.tabs
    navigation.tabs.sticky
    navigation.sections
    navigation.expand
    navigation.path
    toc.follow
    toc.integrate
    navigation.top
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
  - blog: