site_name: Codelogium
site_description: Developer logs, notes, and learning paths
site_url: https://codelogium.github.io
repo_url: https://github.com/codelogium/codelogium
repo_name: codelogium/codelogium
edit_uri: "GitHub"

theme:
  name: material
  language: en
  #custom_dir: overrides
  #logo: assets/logo.png          
  #favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - search.suggest
    - content.code.annotate
    - search.highlight

markdown_extensions:
  - toc:
      title: "Table of content"
      permalink: "¶"
      permalink_title: Permalink 
      toc_depth: "1-6"
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.details
  - attr_list
  - tables
  
nav:
  - Home: index.md
  - Databases:
      - Overview: databases/index.md
      - Postgres vs H2: blog/post/database/postgres-vs-h2.md
      - Hibernate Tips: blog/post/database/hibernate-tips.md
  - Java: 
      - java/index.md
      - blog/post/java/generic-types.md
  - Spring:
      - Overview: spring/index.md
      - JWT Auth: spring/jwt-auth.md
  - Lab:
      - Overview: lab/index.md
  - Blog:
      - Overview: blog/index.md
      - Random Thought: blog/random-thought.md
      - Things I Learned: blog/things-i-learned.md
  - Categories:
      - Java: categories/java.md
      - Programming: categories/programming.md
      - OOP: categories/oop.md

extra:
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alfahami
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alfahami
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/al_fahami

copyright: "© 2025 Codelogium • Crafted with curiosity accompanied by a cup of tea."

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
  - awesome-pages:
  - blog:
  - blogging:
  - categories:
      enabled: true
      categories_folder: categories
      append_categories: false  # This disables the automatic category listing
  - tags
  # - social: can be installed later preferably in a linux machine
  - git-committers:
      repository: codelogium/codelogium.github.io
      branch: main
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago  # or 'timeago', 'datetime'
      enable_creation_date: true